### ISSUE TITLE
Litterbox annotation fails

### ISSUE THREAD

**Issue by IustinPaulenco** [se2p/LitterBox#6]
The annotation feature of the check options fails when used. It gives the following exception:

```
C:\...\_LitterBox>java -jar Litterbox-1.9.full.jar check --path ./Projects\Proiect1\main.sb3 --annotate ./Projects\Proiect1\results.json
Issue immediate_stop_after_say_think was found 1 time(s)
Issue missing_initialization was found 1 time(s)
Issue busy_waiting was found 1 time(s)
Issue duplicate_sprite was found 3 time(s)
Issue sprite_naming was found 4 time(s)
Issue stuttering_movement was found 4 time(s)
Issue boolean_expression was found 1 time(s)
Issue collision was found 5 time(s)
Issue conditional_inside_loop was found 6 time(s)
Issue correct_broadcast was found 2 time(s)
Issue initialisation_of_looks was found 6 time(s)
Issue loop_sensing was found 6 time(s)
Issue parallelisation was found 6 time(s)
Issue timer was found 1 time(s)
Issue used_variables was found 2 time(s)
Issue valid_termination was found 1 time(s)
java.lang.UnsupportedOperationException
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147)
        at de.uni_passau.fim.se2.litterbox.ast.model.metadata.actor.ActorMetadata.addComment(ActorMetadata.java:61)
        at de.uni_passau.fim.se2.litterbox.report.CommentGenerator.addBlockComment(CommentGenerator.java:81)
        at de.uni_passau.fim.se2.litterbox.report.CommentGenerator.generateReport(CommentGenerator.java:48)
        at de.uni_passau.fim.se2.litterbox.analytics.BugAnalyzer.createAnnotatedFile(BugAnalyzer.java:115)
        at de.uni_passau.fim.se2.litterbox.analytics.BugAnalyzer.writeResultToFile(BugAnalyzer.java:79)
        at de.uni_passau.fim.se2.litterbox.analytics.BugAnalyzer.writeResultToFile(BugAnalyzer.java:39)
        at de.uni_passau.fim.se2.litterbox.analytics.FileAnalyzer.checkAndWrite(FileAnalyzer.java:111)
        at de.uni_passau.fim.se2.litterbox.analytics.FileAnalyzer.analyzeFile(FileAnalyzer.java:64)
        at de.uni_passau.fim.se2.litterbox.Main$LitterBoxSubcommand.runAnalysis(Main.java:161)
        at de.uni_passau.fim.se2.litterbox.Main$LitterBoxSubcommand.call(Main.java:150)
        at de.uni_passau.fim.se2.litterbox.Main$LitterBoxSubcommand.call(Main.java:89)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at de.uni_passau.fim.se2.litterbox.Main.main(Main.java:85)
```

my Java version:
```
C:\...\_LitterBox>java --version
java 17.0.12 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)
```

**Comment by b-fein** [comment]
Thanks for the report. I created release 1.9.1 https://github.com/se2p/LitterBox/releases/tag/v1.9.1 with a fix for the issue.
